#!/usr/bin/env node
/**
 * Build script for the dashboard JavaScript.
 * Bundles frontend/main.jsx -> static/app.js with source maps and JSX support.
 * 
 * Usage:
 *   node build.mjs          # Single build
 *   node build.mjs --watch  # Watch mode
 */

import * as esbuild from 'esbuild';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const isWatch = process.argv.includes('--watch');

const buildOptions = {
    entryPoints: [join(__dirname, 'frontend/main.jsx')],
    bundle: true,
    outfile: join(__dirname, 'static/app.js'),
    sourcemap: true,
    minify: !isWatch, // Don't minify in watch mode for faster rebuilds
    format: 'iife',
    target: ['es2020'],
    logLevel: 'info',
    banner: {
        js: '// Generated by esbuild - do not edit directly\n// Source: frontend/\n'
    },
    // JSX configuration - use classic mode with our custom h function
    jsx: 'transform',
    jsxFactory: 'h',
    jsxFragment: 'Fragment',
    loader: {
        '.js': 'jsx',  // Treat .js files as JSX too
        '.jsx': 'jsx'
    }
};

async function build() {
    try {
        if (isWatch) {
            const ctx = await esbuild.context(buildOptions);
            await ctx.watch();
            console.log('Watching for changes...');
        } else {
            const result = await esbuild.build(buildOptions);
            console.log('Build complete:', result);
        }
    } catch (error) {
        console.error('Build failed:', error);
        process.exit(1);
    }
}

build();
